
NAV_ROUTES = [
  "/cliente/pro",
  "/fixtures/today-pro",
  "/picks",
  "/cliente/1x2",
  "/cliente/live-command-center",
  "/cliente/match-center-premium",
  "/cliente/favorites-following",
  "/cliente/shark-ai-pro",
  "/cliente/membresia"
]
TEMPLATE_HREFS_SAMPLE = {
  "{{ url_for(": 235,
  "/clientes": 188,
  "/picks": 116,
  "/fixtures/today-pro": 114,
  "/smart-value-detection": 107,
  "/live-command-center": 102,
  "/shark-ai": 95,
  "/match-center-unified": 93,
  "/static/css/v263_global_design_system_unification.css": 89,
  "/cliente/pro": 45,
  "/static/css/v70_premium_ui.css": 41,
  "/": 37,
  "/cliente/shark-ai-pro": 31,
  "/partidos": 29,
  "/en-directo": 19,
  "/cliente/picks": 18,
  "/logout": 18,
  "/cliente/live-experience": 17,
  "/cliente/live-central": 17,
  "/cliente/1x2": 16,
  "/cliente/favoritos": 15,
  "/live-center": 14,
  "/cliente": 13,
  "/cliente/dashboard-pro": 13,
  "/cuenta": 12,
  "{{ item.href }}": 12,
  "/cliente/partidos": 11,
  "/cliente/rendimiento": 10,
  "/clasificaciones": 10,
  "/admin/real-core": 9,
  "/cliente/today-command": 9,
  "/real-data-health": 9,
  "/cliente/discovery": 9,
  "/mi-cuenta": 8,
  "{{ p.detail_url }}": 8,
  "/planes": 7,
  "/admin": 7,
  "/community": 7,
  "/partidos?force=true": 7,
  "/match-center-real": 7,
  "/api/stability/full-status-v321": 7,
  "/live-ultra": 6,
  "/static/css/v81_commercial.css": 6,
  "/premium": 6,
  "/favoritos": 6,
  "/cliente/cuenta": 6,
  "/hot-match-alerts": 6,
  "/cliente/smart-home": 6,
  "/client-action-center": 6,
  "/admin/picks-manager": 5,
  "/admin/fixtures-sync": 5,
  "/beta": 5,
  "/registro?plan=FREE": 5,
  "/static/css/v91_real_core.css": 5,
  "/alertas": 5,
  "/cliente/shark-ai": 5,
  "/favorites-pro": 5,
  "/cliente-login": 5,
  "/static/css/v245_navigation_unified.css": 5,
  "/bankroll-edge": 5,
  "/static/css/v93_pro.css": 4,
  "/api/v93/status": 4,
  "{{ link.href }}": 4,
  "/admin/telegram-pro": 4,
  "/api/v117/telegram/test": 4,
  "/admin/launch-candidate": 4,
  "/admin/launch": 4,
  "/static/css/v90_legacy_kill.css": 4,
  "/admin/ml-center": 4,
  "/ayuda": 4,
  "/cliente/menu": 4,
  "/cliente/partidos?filtro=hoy": 4,
  "{{ action.href }}": 4,
  "/cliente/shark-ai-real": 4,
  "/static/css/v92_client_panel.css": 4,
  "/picks?force=true": 4,
  "/partidos?date=today": 4,
  "/partido/{{ p.id }}": 4,
  "/live-center-pro": 4,
  "/registro?plan=PRO": 4
}

def nav_audit_status():
    return {
        "ok": True,
        "version": "V349",
        "name": "CLIENT_NAVIGATION_AUDIT_UX_FIX_PRO",
        "nav_routes": NAV_ROUTES,
        "hrefs_detected_top": TEMPLATE_HREFS_SAMPLE,
        "fixes": [
            "single bottom app navigation",
            "dedupe repeated client links",
            "safe bottom spacing",
            "tap targets >= 44px",
            "hide old injected nav buttons",
            "avoid overlays blocking clicks",
            "scroll unlock",
            "mobile safe area"
        ],
        "recommended_checks": [
            "/cliente/pro",
            "/cliente/1x2",
            "/cliente/live-command-center",
            "/cliente/match-center-premium",
            "/cliente/favorites-following",
            "/cliente/membresia",
            "/api/client/navigation-audit/status-v349"
        ],
        "real_only": True
    }
